server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  # 데이터베이스 설정
  datasource:
    # 개발 환경에서는 테스트 컨텍스트 마다 독립된 테스트 컨텍스트를 사용하기 위해 무작위 uuid를 주입
    url: jdbc:h2:mem:${random.uuid};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # 테이블 자동 생성 설정
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:dummy-data.sql

  # JPA/Hibernate 운영 설정
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  # h2 콘솔 활성화
  h2:
    console:
      enabled: true

# 로깅 설정
logging:
  level:
    com.codeit.mission.deokhugam: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# AWS S3 설정
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:dummy-local}
      secret-key: ${AWS_SECRET_ACCESS_KEY:dummy-local}
    s3:
      region: ap-northeast-2
      bucket: ${AWS_BUCKET_NAME:dummy-local}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    groups-order: ASC
    operations-sorter: alpha

naverapi:
  client-id: ${NAVER_CLIENT_ID:dummy-local}
  client-secret: ${NAVER_CLIENT_SECRET:dummy-local}

ocr:
  url: https://api.ocr.space/parse/image
  apikey: ${SPACE_OCR_API_KEY:dummy-local}
