server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  # 데이터베이스 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate 운영 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

# 로깅 설정
logging:
  level:
    com.codeit.mission.deokhugam: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    groups-order: ASC
    operations-sorter: alpha